#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
history_guard.py - block "stale index" commits (P105, 2026-10-05).

Why this exists
  P104 found the main worktree's .git/index frozen at an old state. A plain
  `git commit` from there would have deleted 33 tracked files (still on disk)
  and rolled 11 files back to their 9/21-9/28 content. Rules in CLAUDE.md /
  AGENTS.md only help if the agent reads them; local hooks only help if they
  are installed and not skipped with --no-verify. This script is the shared
  check used by BOTH the local commit-msg hook and the GitHub Actions workflow
  (.github/workflows/history-guard.yml), so the last line of defence does not
  depend on any AI or person remembering anything.

What it flags (per non-merge commit, compared with its first parent)
  1. MASS DELETE : more than MAX_DELETES tracked files deleted in one commit.
  2. ROLLBACK    : a modified file whose new content (blob) is byte-identical
                   to an OLDER version of the same path in history, while the
                   parent has a different (newer) version. That is exactly what
                   a stale index produces.
  3. NO-HOOK (warning only): commit message lacks the trailer
                   "Guard-Checked: tcon-hooks" that the local commit-msg hook
                   adds -> the commit was made without hooks or with --no-verify.

Deliberate exceptions (written in the commit message, visible forever)
  Allow-Mass-Delete: <reason>
  Allow-Revert: <reason>
  Messages generated by `git revert` (start with 'Revert "') are allowed to
  roll back content.

Modes
  --staged --msg-file F   local commit-msg hook: check index vs HEAD
  --range  A..B           CI: check every commit in A..B (A may be all zeros)
  --commit SHA            check a single commit
  Exit code: 0 ok, 1 violation, 2 the check itself could not run.
"""
import argparse
import os
import re
import subprocess
import sys

MAX_DELETES = 5
TRAILER = "Guard-Checked: tcon-hooks"
ZERO = "0" * 40


def git(*args, check=True):
    p = subprocess.run(["git", "-c", "core.quotepath=off"] + list(args),
                       stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if check and p.returncode != 0:
        raise RuntimeError("git %s -> rc=%d %s" % (" ".join(args), p.returncode,
                                                   p.stderr.decode("utf-8", "replace").strip()))
    return p.stdout.decode("utf-8", "replace")


def parse_raw(text):
    """Parse `git diff --raw -z`-like output into [(status, oldblob, newblob, path)]."""
    out = []
    parts = text.split("\0")
    i = 0
    while i < len(parts):
        head = parts[i]
        if not head.startswith(":"):
            i += 1
            continue
        f = head[1:].split()
        # f = [oldmode, newmode, oldsha, newsha, status]
        status = f[4][0]
        path = parts[i + 1] if i + 1 < len(parts) else ""
        out.append((status, f[2], f[3], path))
        i += 2
    return out


def history_blobs(rev, path):
    """All blob ids the path has ever had in the history of rev."""
    txt = git("log", "--raw", "--no-abbrev", "--no-renames", "--format=", rev, "--", path)
    blobs = set()
    for line in txt.splitlines():
        if line.startswith(":"):
            f = line[1:].split("\t")[0].split()
            if len(f) >= 4:
                blobs.add(f[3])
    return blobs


def has_trailer(msg, name):
    return re.search(r"(?mi)^%s\s*:\s*\S" % re.escape(name), msg or "") is not None


def check_changes(changes, parent, msg, label, deleted):
    """changes: list from parse_raw; parent: rev of the older side;
    deleted: paths deleted with rename detection on (a rename is not a delete).
    Returns problems."""
    problems = []
    if len(deleted) > MAX_DELETES and not has_trailer(msg, "Allow-Mass-Delete"):
        problems.append("%s: MASS DELETE - %d tracked files deleted (limit %d): %s%s"
                        % (label, len(deleted), MAX_DELETES, ", ".join(deleted[:10]),
                           " ..." if len(deleted) > 10 else ""))
    is_git_revert = (msg or "").startswith('Revert "')
    if not is_git_revert and not has_trailer(msg, "Allow-Revert") and parent:
        rolled = []
        for status, old, new, path in changes:
            if status != "M" or old == new or new == ZERO:
                continue
            hist = history_blobs(parent, path)
            hist.discard(old)
            if new in hist:
                rolled.append(path)
        if rolled:
            problems.append("%s: ROLLBACK - %d file(s) set back to an older committed version: %s"
                            % (label, len(rolled), ", ".join(rolled[:10])))
    return problems


def check_commit(sha):
    parents = git("rev-list", "--parents", "-n", "1", sha).split()[1:]
    msg = git("log", "-1", "--format=%B", sha)
    if len(parents) > 1:
        return [], []  # merge commits: not checked (stale-index commits are not merges)
    short = sha[:8]
    if parents:
        raw = git("diff-tree", "-r", "-z", "--no-renames", "--no-commit-id", parents[0], sha)
    else:
        return [], []  # root commit
    deleted = git("diff-tree", "-r", "-M", "--no-commit-id", "--name-only", "--diff-filter=D",
                  parents[0], sha).splitlines()
    problems = check_changes(parse_raw(raw), parents[0], msg, short, deleted)
    warnings = []
    if TRAILER.lower() not in msg.lower():
        warnings.append("%s: committed without the local guard hook (no '%s' trailer; "
                        "hooks not installed, or --no-verify)" % (short, TRAILER))
    return problems, warnings


def commits_in_range(rng):
    a, _, b = rng.partition("..")
    if not a or a == ZERO:
        # new branch: only commits not already on main, max 50
        base = "origin/main" if git("rev-parse", "-q", "--verify", "origin/main",
                                    check=False).strip() else "main"
        out = git("rev-list", "--reverse", "--max-count=50", b, "--not", base,
                  check=False).split()
        return out or [git("rev-parse", b).strip()]
    if git("cat-file", "-t", a, check=False).strip() != "commit":
        return [git("rev-parse", b).strip()]  # before-sha unknown (force push): check head only
    return git("rev-list", "--reverse", "%s..%s" % (a, b)).split()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--staged", action="store_true")
    ap.add_argument("--msg-file")
    ap.add_argument("--range")
    ap.add_argument("--commit")
    ap.add_argument("--report")
    a = ap.parse_args()
    try:
        problems, warnings = [], []
        if a.staged:
            msg = ""
            if a.msg_file and os.path.exists(a.msg_file):
                msg = open(a.msg_file, encoding="utf-8", errors="replace").read()
                msg = "\n".join(l for l in msg.splitlines() if not l.startswith("#"))
            head_ok = git("rev-parse", "--verify", "-q", "HEAD", check=False).strip()
            if head_ok:
                raw = git("diff-index", "--cached", "-r", "-z", "--no-renames", "HEAD")
                deleted = git("diff-index", "--cached", "-M", "--name-only", "--diff-filter=D",
                              "HEAD").splitlines()
                problems = check_changes(parse_raw(raw), "HEAD", msg, "staged", deleted)
        elif a.range or a.commit:
            shas = commits_in_range(a.range) if a.range else [git("rev-parse", a.commit).strip()]
            for s in shas:
                p, w = check_commit(s)
                problems += p
                warnings += w
        else:
            ap.error("need --staged, --range or --commit")
    except Exception as e:  # the check itself failed: never treat as pass
        print("HISTORY GUARD CANNOT RUN: %s" % e)
        return 2

    for w in warnings:
        print("WARNING " + w)
    for p in problems:
        print("BLOCKED " + p)
    if a.report:
        with open(a.report, "w", encoding="utf-8") as fh:
            fh.write("\n".join(["BLOCKED " + p for p in problems] + ["WARNING " + w for w in warnings]) + "\n")
    if problems:
        print("")
        print("This looks like a stale .git/index (files deleted or rolled back by accident).")
        print("Fix (index only, files untouched): git restore --staged -- <paths>, then git status.")
        print("Deliberate? Add a trailer to the commit message: 'Allow-Revert: <reason>' or")
        print("'Allow-Mass-Delete: <reason>'.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
